name: MusEDWorks
favicon: null
layout_spectrum: 0.54828
typography_spectrum: 0.34951
title: Design and development studio bringing creative and playful  music­-based technologies to the marketplace.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77427427-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#464647'
    - '#000099'
    - '#a2cd39'
    - '#a906b5'
    - '#11d1d4'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
