name: MusEDWorks
favicon: null
layout_spectrum: 0.5463529536500573
typography_spectrum: 0.3456559937912971
title: Design and development studio that brings creative and playful  music­-based technologies to the marketplace.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77427427-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.07025044993497431
  lightness: 0.5225767919328064
  saturation: 0.9000654735136777
  rhythmicContrast: 0.8494596616365016
purpose: []
